services:
    six-strings:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3940:80'
        restart: always
        container_name: six-strings
        environment:
            - NODE_ENV=production
        env_file:
            - .env
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '3941:3941'
        container_name: six-strings-backend
        restart: unless-stopped
        environment:
            - NODE_ENV=production
        env_file:
            - ./backend/.env
