export * from './login/LoginPage'
export * from './registration/Registration'
export * from './HomePage/HomPage'
export * from './catalog/CatalogPage'
export * from './categories/CategoriesPage'
export * from './basket/BasketPage'
export * from './favorites/FavoritesPage'
export * from './saler/MyProduct/MyProductPage'