// src/storage/actionTypes.ts

// Guitar Actions
export const GET_GUITARS_START = 'GET_GUITARS_START';
export const GET_GUITARS_SUCCESS = 'GET_GUITARS_SUCCESS';
export const GET_GUITARS_FAILURE = 'GET_GUITARS_FAILURE';

// Basket Actions
export const GET_BASKET_START = 'GET_BASKET_START';
export const GET_BASKET_SUCCESS = 'GET_BASKET_SUCCESS';
export const GET_BASKET_FAILURE = 'GET_BASKET_FAILURE';

export const ADD_TO_BASKET_START = 'ADD_TO_BASKET_START';
export const ADD_TO_BASKET_SUCCESS = 'ADD_TO_BASKET_SUCCESS';
export const ADD_TO_BASKET_FAILURE = 'ADD_TO_BASKET_FAILURE';

export const UPDATE_BASKET_ITEM_START = 'UPDATE_BASKET_ITEM_START';
export const UPDATE_BASKET_ITEM_SUCCESS = 'UPDATE_BASKET_ITEM_SUCCESS';
export const UPDATE_BASKET_ITEM_FAILURE = 'UPDATE_BASKET_ITEM_FAILURE';

export const REMOVE_FROM_BASKET_START = 'REMOVE_FROM_BASKET_START';
export const REMOVE_FROM_BASKET_SUCCESS = 'REMOVE_FROM_BASKET_SUCCESS';
export const REMOVE_FROM_BASKET_FAILURE = 'REMOVE_FROM_BASKET_FAILURE';

export const CLEAR_BASKET_START = 'CLEAR_BASKET_START';
export const CLEAR_BASKET_SUCCESS = 'CLEAR_BASKET_SUCCESS';
export const CLEAR_BASKET_FAILURE = 'CLEAR_BASKET_FAILURE';

// User Authentication Actions
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// Favorite Actions (Placeholder - can be expanded later)
export const GET_FAVORITES_START = 'GET_FAVORITES_START';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_FAILURE = 'GET_FAVORITES_FAILURE';

export const ADD_TO_FAVORITES_START = 'ADD_TO_FAVORITES_START';
export const ADD_TO_FAVORITES_SUCCESS = 'ADD_TO_FAVORITES_SUCCESS';
export const ADD_TO_FAVORITES_FAILURE = 'ADD_TO_FAVORITES_FAILURE';

export const REMOVE_FROM_FAVORITES_START = 'REMOVE_FROM_FAVORITES_START';
export const REMOVE_FROM_FAVORITES_SUCCESS = 'REMOVE_FROM_FAVORITES_SUCCESS';
export const REMOVE_FROM_FAVORITES_FAILURE = 'REMOVE_FROM_FAVORITES_FAILURE';
